sw/naves/models.py
from bson.objectid import ObjectId
from config.db import db

def get_naves():
    return db.naves.find()

def get_nave(oid):
    filtro = {"_id": ObjectId(oid)}
    return db.naves.find_one(filtro)

def criar_nave(nave):
    return db.naves.insert_one(nave)

def modificar_nave(oid, nave):
    if isinstance(oid, str):
        oid = {"_id": ObjectId(oid)}

    return db.naves.update_one(
        oid,
        {"$set": nave}
    )

def deletar_nave(oid):
    if isinstance(oid, str):
        oid = {"_id": ObjectId(oid)}

    return db.naves.delete_one(oid)

sw/personagens/models.py
from bson.objectid import ObjectId
from config.db import db

def get_personagens():
    return db.personagens.find()

def get_personagem(oid):
    filtro = {"_id": ObjectId(oid)}
    return db.personagens.find_one(filtro)

def criar_personagens(personagem):
    return db.personagens.insert_one(personagem)

def modificar_personagens(oid, personagem):
    if isinstance(oid, str):
        oid = {"_id": ObjectId(oid)}

    return db.personagens.update_one(
        oid,
        {"$set": personagem}
    )

def deletar_personagem(oid):
    if isinstance(oid, str):
        oid = {"_id": ObjectId(oid)}

    return db.personagens.delete_one(oid)

sw/naves/blueprint.py
import flask
from bson.json_util import dumps
# from sw.naves import models
from . import models # ^^^ mesma coisa
from config.api import cabecalhos

bp = flask.Blueprint("naves", __name__, url_prefix="/naves")

@bp.route("")
def index():
    naves = list(models.get_naves())
    return flask.render_template("naves/index.html",
                                 naves=naves)
    #                                  ^^^^^ variável na função
    #                            ^^^^^ variável no template

@bp.route("/<id>/editar", methods=["GET", "POST"])
def editar_nave(id):
    if flask.request.method == 'GET':
        nave = models.get_nave(id)
        return flask.render_template("naves/edit.html",
                                     verbo="Editar",
                                     nave=nave)

    elif flask.request.method == 'POST':
        novo_nome = flask.request.form['nave_nome']
        models.modificar_nave(id, {'nome': novo_nome})
        return flask.redirect(flask.url_for("naves.index"))

@bp.route("/criar", methods=["GET", "POST"])
def criar_nave():
    if flask.request.method == 'GET':
        return flask.render_template("naves/edit.html",
                                     verbo="Criar")

    elif flask.request.method == 'POST':
        nome = flask.request.form['nave_nome']
        models.criar_nave({'nome': nome})
        return flask.redirect(flask.url_for("naves.index"))

@bp.route("api")
def listar_naves():
    naves = dumps(list(models.get_naves()))
    return flask.Response(naves, headers=cabecalhos)

@bp.route("api", methods=["POST"])
def criar_nave_api():
    nave = flask.request.json
    result = models.criar_nave(nave)
    return flask.jsonify({"id": str(result.inserted_id)})

@bp.route("api/<int:id>")
def get_nave(id):
    nave = dumps(list(models.get_naves())[id])
    return flask.Response(nave, headers=cabecalhos)

@bp.route("/<id>/deletar")
def deletar_nave(id):
    models.deletar_nave(id)
    return flask.redirect(flask.url_for("naves.index"))

@bp.route("api/<int:id>", methods=["PUT"])
def modificar_nave(id):
    nave = flask.request.json
    naves = list(models.get_naves())
    nave_velha = naves[id]
    result = models.modificar_nave(
        {"_id": nave_velha["_id"]},
        nave
    )
    return flask.jsonify({
        "modificados": result.modified_count
    })

sw/personagens/blueprint.py
import flask
from bson.json_util import dumps
# from sw.personagens import models
from . import models # ^^^ mesma coisa
from config.api import cabecalhos

bp = flask.Blueprint("personagens", __name__, url_prefix="/personagens")

@bp.route("")
def index():
    personagens = list(models.get_personagens())
    return flask.render_template("personagens/index.html",
                                 personagens=personagens)
    #                                  ^^^^^ variável na função
    #                            ^^^^^ variável no template

@bp.route("/<id>/editar", methods=["GET", "POST"])
def editar_personagem(id):
    if flask.request.method == 'GET':
        personagem = models.get_personagem(id)
        return flask.render_template("personagens/edit.html",
                                     personagem=personagem)

    elif flask.request.method == 'POST':
        novo_nome = flask.request.form['personagem_nome']
        models.modificar_personagens(id, {'nome': novo_nome})
        return flask.redirect(flask.url_for("personagens.index"))

@bp.route("")
def listar_personagens():
    personagens = dumps(list(models.get_personagens()))
    return flask.Response(personagens, headers=cabecalhos)

@bp.route("/criar", methods=["GET", "POST"])
def criar_personagem():
    if flask.request.method == 'GET':
        return flask.render_template("personagens/edit.html",
                                     verbo="Criar")

    elif flask.request.method == 'POST':
        nome = flask.request.form['personagem_nome']
        models.criar_personagens({'nome': nome})
        return flask.redirect(flask.url_for("personagens.index"))

@bp.route("api/<int:id>")
def get_personagem(id):
    personagem = dumps(list(models.get_personagens())[id])
    return flask.Response(personagem, headers=cabecalhos)

@bp.route("/<id>/deletar")
def deletar_personagem(id):
    models.deletar_personagem(id)
    return flask.redirect(flask.url_for("personagens.index"))

@bp.route("api/<int:id>", methods=["PUT"])
def modificar_personagem(id):
    personagem = flask.request.json
    personagens = list(models.get_personagens())
    personagem_velha = personagens[id]
    result = models.modificar_personagem(
        {"_id": personagem_velha["_id"]},
        personagem
    )
    return flask.jsonify({
        "modificados": result.modified_count
    })

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Api SW</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/naves/edit.html
{% extends "base.html" %}

{% block content %}
<h1>{{ verbo}} nave {% if nave %} {{ nave._id }}{% endif %}</h1>

<form method="post">
    <p>
        Nome: 
        <input type="text"
               name="nave_nome"
               value="{% if nave %}{{ nave.nome }}{% endif %}">
    </p>
    <p>
        <input type="submit" value="Salvar">
    </p>
</form>
{% endblock %}

templates/naves/index.html
{% extends "base.html" %}

{% block content %}
<h1>Naves</h1>

<table>
    <tr>
        <th>Nome</th>
        <th>ID</th>
        <th>Ações</th>
    </tr>
    {% for nave in naves %}
    <tr>
        <td>{{ nave.nome }}</td>
        <td>{{ nave._id }}</td>
        <td>       <!-- url_for('naves.editar_nave', id=nave._id) -->
            <a href="{{ url_for('naves.editar_nave', id=nave._id) }}">Editar</a>
            <a href="{{ url_for('naves.deletar_nave', id=nave._id) }}">Deletar</a>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td><a href="{{ url_for('naves.criar_nave') }}">+</a>>Criar</a></td>
    </tr>
</table>
{% endblock %}

templates/personagens/edit.html
{% extends "base.html" %}

{% block content %}
<h1>{{ verbo}} personagem {% if personagem %} {{ personagem._id }}{% endif %}</h1>

<form method="post">
    <p>
        Nome: 
        <input type="text"
                     name="personagem_nome"
                     value="{% if personagem %}{{ personagem.nome }}{% endif %}">
    </p>
    <p>
        <input type="submit" value="Salvar">
    </p>
</form>
{% endblock %}

templates/personagens/index.html
{% extends "base.html" %}

{% block content %}
<h1>Personagens</h1>

<table>
    <tr>
        <th>Nome</th>
        <th>ID</th>
        <th>Ações</th>
    </tr>
    {% for personagem in personagens %}
    <tr>
        <td>{{ personagem.nome }}</td>
        <td>{{ personagem._id }}</td>
        <td>       <!-- url_for('naves.editar_nave', id=nave._id) -->
            <a href="{{ url_for('personagens.editar_personagem', id=personagem._id) }}">Editar</a>
            <a href="{{ url_for('personagens.deletar_personagem', id=personagem._id) }}">Deletar</a>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td><a href="{{ url_for('personagens.criar_personagem') }}">+</a>>Criar</a></td>
    </tr>
</table>
{% endblock %}